name: movie_app
description: "movie application sample."
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  cached_network_image: ^3.2.3
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.8
  mysql1: ^0.20.0
  drift: ^2.0.0
  shelf: ^1.3.0
  shelf_router: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.0
  drift_dev: ^2.0.0
  build_runner: ^2.0.0
  hotreloader: ^4.1.0
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
